title: Evan Freeman
email: evan.e.freeman@gmail.com
description: "Evan Freeman is a veteran software engineer at HubSpot with extensive knowledge of frontend and backend development.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "//www.evanfreeman.me" # the base hostname & protocol for your site
paginate: 25
paginate_path: "/posts/page/:num/"
twitter_username: codeundrum
github_username: evanfreeman
google_plus_username: evanfreeman

# Build settings
markdown: kramdown
markdown_ext: "md"
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
